name: date_mirror
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  intl:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  image_path: "assets\\images\\mirror.png"
  adaptive_icon_background: "assets\\images\\mirror.png"
  adaptive_icon_foreground: "assets\\images\\mirror.png"